name: Deploy Drafts Site to Cloudflare Pages
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy-drafts-site
jobs:
  build:
    name: Deploy to Cloudfalre Pages
    runs-on: ubuntu-latest
    concurrency: build-drafts-site
    steps:
      - uses: actions/checkout@v3
        with:
          repository: immersive-translate/site
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: ./package-lock.json
      - name: Build website
        run: npm i && cd drafts && npm run build
      - name: Upload R2
        run: DEPLOYMENT_STAGE=production FOLDER=./drafts/dist/ ID=drafts make upload
        env:
          CLOUFLARE_AWS_ACCESS_KEY_ID: ${{secrets.CLOUFLARE_AWS_ACCESS_KEY_ID}}
          CLOUFLARE_AWS_SECRET_ACCESS_KEY: ${{secrets.CLOUFLARE_AWS_SECRET_ACCESS_KEY}}
          CLOUFLARE_AWS_ENDPOINT: ${{secrets.CLOUFLARE_AWS_ENDPOINT}}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.IMMERSIVE_CLOUDFLARE_API_TOKEN }}
          accountId: ${{secrets.IMMERSIVE_CLOUDFLARE_ACCOUNT_ID}}
          projectName: immersivetranslate-drafts
          directory: drafts/dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
