name: Deploy Activities Site to Cloudflare Pages
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy-activities
jobs:
  build:
    name: Deploy to R2
    runs-on: ubuntu-latest
    concurrency: build-activities
    steps:
      - uses: actions/checkout@v3
        with:
          repository: immersive-translate/site
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      # check to main branch
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: ./package-lock.json
      - name: Build website
        run: npm i && cd activities &&  npm run build
      - name: Upload R2
        run: DEPLOYMENT_STAGE=production FOLDER=./activities/dist/ ID=activities make upload
        env:
          CLOUFLARE_AWS_ACCESS_KEY_ID: ${{secrets.CLOUFLARE_AWS_ACCESS_KEY_ID}}
          CLOUFLARE_AWS_SECRET_ACCESS_KEY: ${{secrets.CLOUFLARE_AWS_SECRET_ACCESS_KEY}}
          CLOUFLARE_AWS_ENDPOINT: ${{secrets.CLOUFLARE_AWS_ENDPOINT}}